### ISSUE TITLE
Will this project be maintained?

### ISSUE THREAD

**Issue by acmh** [jotapsl/wastedjs#17]
Hi @joaopslins, congrats for this amazing project. I noticed that this repo is without contributions. Do you will maintain this project or it is closed?

**Comment by joaopslins** [comment]
@acmh no, we will restart from scratch, when @vtcb wants to.

**Comment by vtcb** [comment]
@joaopslins, departed?

**Comment by joaopslins** [comment]
@vtcb split?

**Comment by joaopslins** [comment]
@vtcb @acmh I'm working on this again in the `react-refactor` branch, all help is appreciated, I'm counting on you guys.
